#Github actions template (deploying to Docker hub)

name: Build and Push the image

on:
  push:
    branches:
      - master

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t iamsthita1/scania:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push iamsthita1/scania:${{ github.sha }}
        
